### ISSUE TITLE
Improve .couchappignore

### ISSUE THREAD

**Issue by BigBlueHat** [couchapp/couchapp#204]
People still get confused...
http://stackoverflow.com/questions/11334089/ignore-folders-in-couchappignore

**Comment by awgrover** [comment]
It appears that in .couchappignore, the regex is matching from the head of the filename. A "^" is redundant (but implied). And, of course it's _each_ element of the filename, e.g. "views/bob.txt" and "bob.txt" will both be matched by ".*\\.txt"

**Comment by iblis17** [comment]
@awgrover 
How about this patch?
This will remove the implied "^". 
```diff
diff --git a/couchapp/localdoc.py b/couchapp/localdoc.py
index e095bf5..61a7d92 100644
--- a/couchapp/localdoc.py
+++ b/couchapp/localdoc.py
@@ -281,7 +281,7 @@ class LocalDoc(object):

     def check_ignore(self, item):
         for i in self.ignores:
-            match = re.match(i, item)
+            match = re.search(i, item)
             if match:
                 logger.debug("ignoring %s" % item)
                 return True
```

**Comment by iblis17** [comment]
@BigBlueHat please checkout PR #243 ... and there are tons of test cases.

**Comment by natevw** [comment]
Any plans for this? I'm hoping to add .couchappignore support to a simple little node.js helper and realizing the current format is pretty limited. What I might do with my app is simply match against the full (well, relative to the ddoc root) path.

This would allow the user pretty much full control (e.g. choose whether to ^ anchor, patterns for subfolder combinations, etc.) and also without having to generate tons of combinatoric path parts like PR #243 does.

Obviously not 100% compatible with the original (current) behavior here but I don't foresee much trouble with it in practice. I reviewed a few couchappignore files through github search and most were fairly simple.

**Comment by iblis17** [comment]
@natevw I can merge #243 into master branch, and let you start to work on your proposal.
(although, I still have no idea about the node.js helper is)

**Comment by iblis17** [comment]
The changes in #243 got merged

**Comment by natevw** [comment]
@iblis17 Thanks. What do you think of simplifying that to just pass the relative path?

I did this in my [putdoc](https://github.com/natevw/putdoc) helper which I mentioned above. It does just the push part for some simple couchapps. I think it is the most flexible.

By passing the relative path to the regex (and using `re.search` instead of `re.match` in Python), the benefits are:

* very simple to implement, don't need to test each individual path component combination
* still behaves the same with simple strings like `"node_modules"` or `"\\.*.exe"`
* allows the author to control whether it anchors ^ or not
* also gives more control over subdirectories and stuff

So I hope the real couchapp tool might consider doing the same, just testing a path like "node_modules/.bin/some_install" once against a regex like `/node_modules/`.

**Comment by iblis17** [comment]
@natevw well, I think I already implemented some in #243, like relative path matching. But it's quite long time ago, and I cannot recall what already support in master :p.

**Comment by natevw** [comment]
It looks like in #243 you now check against a lot of combinations but still have some of the old behavior.

I might be reading the code wrong but AFAICT, by the time it gets to "foo/bar/baz.json" it uses `re.match` against a whole bunch of things.

When entering foo:

* foo
* /foo

When entering bar:

* foo
* foo/bar
* /foo
* /foo/bar

When reaching baz.json:

* foo
* foo/bar
* foo/bar/baz.json
* bar
* bar/baz.json
* baz.json
* /foo
* /foo/bar
* /foo/bar/baz.json
* /bar
* /bar/baz.json
* /baz.json

---

I'd recommend switching to `re.search` as you proposed earlier, and then only match one thing (the full relative path) at each level:

Enter foo:

* foo

Enter bar:

* foo/bar

Reach baz.json:

* foo/bar/baz.json

Maybe we should pass directories as `foo/` and `foo/bar/` when entering them?

**Comment by iblis17** [comment]
> I'd recommend switching to `re.search` (which is anchored only if RegEx wants it) as you proposed earlier, and then only test one string (the full relative path) at each level:

I don't get "only test one string at each level". Just want to get rid of input like "/..." only?

Would you send a PR to clearify it, and at the sometime, do not need to change test cases, then we can check which test cases in master failed/might change.

**Comment by natevw** [comment]
@iblis17 I submitted #246 to show what I'm talking about. I wasn't able to run tests locally, but hopefully you can take a look?

This is similar to your original suggestion at https://github.com/couchapp/couchapp/issues/204#issuecomment-205642247 only I think it's going to work much better now that check_ignores is getting passed the `rel_path` instead of `filename`.
